xl - xaxxon's library: benchmark/aligned_string.cpp File Reference
aligned_string.cpp File Reference
#include <iostream>
#include <sstream>
#include <benchmark/benchmark.h>
#include <vector>
#include "aligned_string/aligned_string.h"
#include "aligned_string/static_buffer.h"
Functions
std::string gen_random (const int len, char c='\0')
static void aligned_short_string_strchr_miss (benchmark::State &state)
BENCHMARK (aligned_short_string_strchr_miss)
static void std_short_string_find_miss (benchmark::State &state)
BENCHMARK (std_short_string_find_miss)
static void aligned_short_string_strchr_hit (benchmark::State &state)
BENCHMARK (aligned_short_string_strchr_hit)
static void std_short_string_find_hit (benchmark::State &state)
BENCHMARK (std_short_string_find_hit)
static void aligned_short_string_strchr_hit_first (benchmark::State &state)
BENCHMARK (aligned_short_string_strchr_hit_first)
static void std_short_string_find_hit_first (benchmark::State &state)
BENCHMARK (std_short_string_find_hit_first)
static void std_short_string_raw_strchr_hit_first (benchmark::State &state)
BENCHMARK (std_short_string_raw_strchr_hit_first)
template<class StringType >
vector< StringType > make_strings (size_t count, size_t length, char contents='\0')
static void aligned_short_string_strchr_random (benchmark::State &state)
BENCHMARK (aligned_short_string_strchr_random)
static void aligned_short_string_strchr_random_expect_no_match (benchmark::State &state)
BENCHMARK (aligned_short_string_strchr_random_expect_no_match)
static void std_string_strchr_random (benchmark::State &state)
BENCHMARK (std_string_strchr_random)
static void std_string_find_random (benchmark::State &state)
BENCHMARK (std_string_find_random)
static void aligned_short_string_equals (benchmark::State &state)
BENCHMARK (aligned_short_string_equals)
static void std_short_string_equals (benchmark::State &state)
BENCHMARK (std_short_string_equals)
void register_equality_tests ()
Function Documentation
gen_random()
std::string gen_random (const int len, char c = '\0')
Definition at line 16 of file aligned_string.cpp.
Referenced by make_strings(), std_string_find_random(), and std_string_strchr_random().
aligned_short_string_strchr_miss()
static void aligned_short_string_strchr_miss (benchmark::State & state) static
Definition at line 38 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [1/13]
BENCHMARK (aligned_short_string_strchr_miss)
Referenced by aligned_short_string_equals(), aligned_short_string_strchr_hit(), aligned_short_string_strchr_hit_first(), aligned_short_string_strchr_miss(), aligned_short_string_strchr_random(), aligned_short_string_strchr_random_expect_no_match(), std_short_string_equals(), std_short_string_find_hit(), std_short_string_find_hit_first(), std_short_string_find_miss(), std_short_string_raw_strchr_hit_first(), std_string_find_random(), and std_string_strchr_random().
std_short_string_find_miss()
static void std_short_string_find_miss (benchmark::State & state) static
Definition at line 51 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [2/13]
BENCHMARK (std_short_string_find_miss)
aligned_short_string_strchr_hit()
static void aligned_short_string_strchr_hit (benchmark::State & state) static
Definition at line 66 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [3/13]
BENCHMARK (aligned_short_string_strchr_hit)
std_short_string_find_hit()
static void std_short_string_find_hit (benchmark::State & state) static
Definition at line 81 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [4/13]
BENCHMARK (std_short_string_find_hit)
aligned_short_string_strchr_hit_first()
static void aligned_short_string_strchr_hit_first (benchmark::State & state) static
Definition at line 96 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [5/13]
BENCHMARK (aligned_short_string_strchr_hit_first)
std_short_string_find_hit_first()
static void std_short_string_find_hit_first (benchmark::State & state) static
Definition at line 110 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [6/13]
BENCHMARK (std_short_string_find_hit_first)
std_short_string_raw_strchr_hit_first()
static void std_short_string_raw_strchr_hit_first (benchmark::State & state) static
Definition at line 126 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [7/13]
BENCHMARK (std_short_string_raw_strchr_hit_first)
make_strings()
template<class StringType > vector<StringType> make_strings (size_t count, size_t length, char contents = '\0')
Definition at line 145 of file aligned_string.cpp.
References gen_random().
Referenced by register_equality_tests().
aligned_short_string_strchr_random()
static void aligned_short_string_strchr_random (benchmark::State & state) static
Definition at line 156 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [8/13]
BENCHMARK (aligned_short_string_strchr_random)
aligned_short_string_strchr_random_expect_no_match()
static void aligned_short_string_strchr_random_expect_no_match (benchmark::State & state) static
Definition at line 170 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [9/13]
BENCHMARK (aligned_short_string_strchr_random_expect_no_match)
std_string_strchr_random()
static void std_string_strchr_random (benchmark::State & state) static
Definition at line 186 of file aligned_string.cpp.
References BENCHMARK(), and gen_random().
BENCHMARK() [10/13]
BENCHMARK (std_string_strchr_random)
std_string_find_random()
static void std_string_find_random (benchmark::State & state) static
Definition at line 201 of file aligned_string.cpp.
References BENCHMARK(), and gen_random().
BENCHMARK() [11/13]
BENCHMARK (std_string_find_random)
aligned_short_string_equals()
static void aligned_short_string_equals (benchmark::State & state) static
Definition at line 219 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [12/13]
BENCHMARK (aligned_short_string_equals)
std_short_string_equals()
static void std_short_string_equals (benchmark::State & state) static
Definition at line 232 of file aligned_string.cpp.
References BENCHMARK().
BENCHMARK() [13/13]
BENCHMARK (std_short_string_equals)
register_equality_tests()
void register_equality_tests ()
Definition at line 245 of file aligned_string.cpp.
References make_strings().