xl - xaxxon's library: benchmark/benchmark.cpp File Reference
benchmark.cpp File Reference
#include <benchmark/benchmark.h>
Functions
void register_equality_tests ()
static void no_op (benchmark::State &state)
BENCHMARK (no_op)
int main (int argc, char **argv)
Function Documentation
register_equality_tests()
void register_equality_tests ()
Definition at line 245 of file aligned_string.cpp.
References make_strings().
no_op()
static void no_op (benchmark::State & state) static
Definition at line 9 of file benchmark.cpp.
References BENCHMARK().
BENCHMARK()
BENCHMARK (no_op)
Referenced by no_op().
main()
int main (int argc, char ** argv)
Definition at line 19 of file benchmark.cpp.