xl - xaxxon's library: xl::RegexResultStd Class Reference
xl::RegexResultStd Class Reference
#include <regex_std.h>
Public Member Functions
RegexResultStd (std::string_view string, std::regex const &regex)
RegexResultStd (zstring_view regex_string, zstring_view string)
xl::string_view prefix ()
char const * suffix ()
xl::string_view operator[] (size_t n) const
auto size () const
bool empty () const
bool length (size_t n=0) const
operator bool () const
Detailed Description
Definition at line 13 of file regex_std.h.
Constructor & Destructor Documentation
RegexResultStd() [1/2]
xl::RegexResultStd::RegexResultStd (std::string_view string, std::regex const & regex) inline
Definition at line 18 of file regex_std.h.
Referenced by xl::RegexStd::match().
RegexResultStd() [2/2]
xl::RegexResultStd::RegexResultStd (zstring_view regex_string, zstring_view string) inline
Definition at line 24 of file regex_std.h.
Member Function Documentation
prefix()
xl::string_view xl::RegexResultStd::prefix () inline
Definition at line 29 of file regex_std.h.
suffix()
char const* xl::RegexResultStd::suffix () inline
Definition at line 36 of file regex_std.h.
operator[]()
xl::string_view xl::RegexResultStd::operator[] (size_t n) const inline
Definition at line 41 of file regex_std.h.
size()
auto xl::RegexResultStd::size () const inline
Definition at line 46 of file regex_std.h.
Referenced by xl::templates::Template::compile().
empty()
bool xl::RegexResultStd::empty () const inline
Definition at line 51 of file regex_std.h.
Referenced by operator bool().
length()
bool xl::RegexResultStd::length (size_t n = 0) const inline
Definition at line 56 of file regex_std.h.
operator bool()
xl::RegexResultStd::operator bool () const inline
Returns true if the regex matched anything
Returns
whether the regex matched anything
Definition at line 65 of file regex_std.h.
References empty().
The documentation for this class was generated from the following file:
include/xl/regex/regex_std.h