xl - xaxxon's library: xl::log::Log< LevelsT, SubjectsT > Class Template Reference
xl::log::Log< LevelsT, SubjectsT > Class Template Reference
#include <log.h>
Classes
struct LogMessage
Public Types
using Levels = log::LogLevelsBase< LevelsT >
using Subjects = log::LogSubjectsBase< SubjectsT >
using LevelsUnderlyingType = std::underlying_type_t< typename Levels::Levels >
using SubjectsUnderlyingType = std::underlying_type_t< typename Subjects::Subjects >
using CallbackT = std::function< void(LogMessage const &message)>
Public Member Functions
auto subjects () const
auto levels () const
auto get (typename Levels::Levels level)
auto get (typename Subjects::Subjects subject)
std::string get_status_string ()
bool set_level_status (typename Levels::Levels level, bool new_status)
bool get_level_status (typename Levels::Levels level) const
void set_all_subjects (bool new_status)
void set_all_levels (bool new_status)
bool set_subject_status (typename Subjects::Subjects subject, bool new_status)
bool get_subject_status (typename Subjects::Subjects subject) const
Log ()
Log (std::string filename)
Log (CallbackT log_callback)
void clear_callbacks ()
CallbackT & add_callback (CallbackT callback)
CallbackT & add_callback (std::ostream &ostream, std::string prefix="")
void remove_callback (CallbackT &callback)
void enable_status_file (std::string filename, bool force_reset=false)
void disable_status_file ()
bool is_status_file_enabled () const
void log (typename Levels::Levels level, typename Subjects::Subjects subject, xl::zstring_view const &string)
Public Attributes
std::vector< bool > level_status
std::vector< bool > subject_status
std::unique_ptr< LogStatusFile > log_status_file
Static Public Attributes
static constexpr LevelsUnderlyingType level_count = static_cast<LevelsUnderlyingType>(Levels::Levels::LOG_LAST_LEVEL)
static constexpr SubjectsUnderlyingType subject_count = static_cast<SubjectsUnderlyingType>(Subjects::Subjects::LOG_LAST_SUBJECT)
Detailed Description
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects>
class xl::log::Log< LevelsT, SubjectsT >
Objects of this type take messages to be logged and route them to the registered callback.
Template Parameters
Levels must provide an enum named Levels and static std::string const & get_level_name(Levels)
Subjects must provide an enum named Subjects and static std::string const & get_subject_name(Subjects)
Definition at line 116 of file log.h.
Member Typedef Documentation
Levels
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> using xl::log::Log< LevelsT, SubjectsT >::Levels = log::LogLevelsBase<LevelsT>
Definition at line 287 of file log.h.
Subjects
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> using xl::log::Log< LevelsT, SubjectsT >::Subjects = log::LogSubjectsBase<SubjectsT>
Definition at line 288 of file log.h.
LevelsUnderlyingType
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> using xl::log::Log< LevelsT, SubjectsT >::LevelsUnderlyingType = std::underlying_type_t<typename Levels::Levels>
Definition at line 290 of file log.h.
SubjectsUnderlyingType
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> using xl::log::Log< LevelsT, SubjectsT >::SubjectsUnderlyingType = std::underlying_type_t<typename Subjects::Subjects>
Definition at line 291 of file log.h.
CallbackT
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> using xl::log::Log< LevelsT, SubjectsT >::CallbackT = std::function<void(LogMessage const & message)>
Definition at line 329 of file log.h.
Constructor & Destructor Documentation
Log() [1/3]
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> xl::log::Log< LevelsT, SubjectsT >::Log () inline
Definition at line 437 of file log.h.
Log() [2/3]
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> xl::log::Log< LevelsT, SubjectsT >::Log (std::string filename) inline
Definition at line 442 of file log.h.
Log() [3/3]
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> xl::log::Log< LevelsT, SubjectsT >::Log (CallbackT log_callback) inline
Definition at line 445 of file log.h.
Member Function Documentation
subjects()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> auto xl::log::Log< LevelsT, SubjectsT >::subjects () const inline
Definition at line 296 of file log.h.
levels()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> auto xl::log::Log< LevelsT, SubjectsT >::levels () const inline
Definition at line 300 of file log.h.
get() [1/2]
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> auto xl::log::Log< LevelsT, SubjectsT >::get (typename Levels::Levels level) inline
Definition at line 304 of file log.h.
get() [2/2]
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> auto xl::log::Log< LevelsT, SubjectsT >::get (typename Subjects::Subjects subject) inline
Definition at line 308 of file log.h.
get_status_string()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> std::string xl::log::Log< LevelsT, SubjectsT >::get_status_string () inline
Definition at line 373 of file log.h.
set_level_status()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> bool xl::log::Log< LevelsT, SubjectsT >::set_level_status (typename Levels::Levels level, bool new_status) inline
Definition at line 387 of file log.h.
get_level_status()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> bool xl::log::Log< LevelsT, SubjectsT >::get_level_status (typename Levels::Levels level) const inline
Definition at line 399 of file log.h.
Referenced by xl::log::LogStatusFile::initialize_from_log().
set_all_subjects()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> void xl::log::Log< LevelsT, SubjectsT >::set_all_subjects (bool new_status) inline
Definition at line 407 of file log.h.
set_all_levels()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> void xl::log::Log< LevelsT, SubjectsT >::set_all_levels (bool new_status) inline
Definition at line 413 of file log.h.
set_subject_status()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> bool xl::log::Log< LevelsT, SubjectsT >::set_subject_status (typename Subjects::Subjects subject, bool new_status) inline
Definition at line 420 of file log.h.
get_subject_status()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> bool xl::log::Log< LevelsT, SubjectsT >::get_subject_status (typename Subjects::Subjects subject) const inline
Definition at line 430 of file log.h.
Referenced by xl::log::LogStatusFile::initialize_from_log().
clear_callbacks()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> void xl::log::Log< LevelsT, SubjectsT >::clear_callbacks () inline
Definition at line 450 of file log.h.
add_callback() [1/2]
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> CallbackT& xl::log::Log< LevelsT, SubjectsT >::add_callback (CallbackT callback) inline
Definition at line 454 of file log.h.
add_callback() [2/2]
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> CallbackT& xl::log::Log< LevelsT, SubjectsT >::add_callback (std::ostream & ostream, std::string prefix = "") inline
Definition at line 459 of file log.h.
References xl::log::Log< LevelsT, SubjectsT >::LogMessage::string.
remove_callback()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> void xl::log::Log< LevelsT, SubjectsT >::remove_callback (CallbackT & callback) inline
If the callback was passed in as a reference wrapper, this can find any corresponding entries and remove them
Parameters
t pass in the object to find (not as a reference wrapper)
Definition at line 469 of file log.h.
enable_status_file()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> void xl::log::Log< LevelsT, SubjectsT >::enable_status_file (std::string filename, bool force_reset = false) inline
Causes a status file with the given name to be maintained with the current settings of this log object
Definition at line 487 of file log.h.
disable_status_file()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> void xl::log::Log< LevelsT, SubjectsT >::disable_status_file () inline
Definition at line 492 of file log.h.
is_status_file_enabled()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> bool xl::log::Log< LevelsT, SubjectsT >::is_status_file_enabled () const inline
Definition at line 496 of file log.h.
log()
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> void xl::log::Log< LevelsT, SubjectsT >::log (typename Levels::Levels level, typename Subjects::Subjects subject, xl::zstring_view const & string) inline
Definition at line 501 of file log.h.
References xl::basic_zstring_view< CharT, Traits >::c_str(), and xl::templates::log.
Member Data Documentation
level_count
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> constexpr LevelsUnderlyingType xl::log::Log< LevelsT, SubjectsT >::level_count = static_cast<LevelsUnderlyingType>(Levels::Levels::LOG_LAST_LEVEL) static
Definition at line 293 of file log.h.
subject_count
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> constexpr SubjectsUnderlyingType xl::log::Log< LevelsT, SubjectsT >::subject_count = static_cast<SubjectsUnderlyingType>(Subjects::Subjects::LOG_LAST_SUBJECT) static
Definition at line 294 of file log.h.
level_status
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> std::vector<bool> xl::log::Log< LevelsT, SubjectsT >::level_status
Definition at line 332 of file log.h.
subject_status
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> std::vector<bool> xl::log::Log< LevelsT, SubjectsT >::subject_status
Definition at line 335 of file log.h.
log_status_file
template<class LevelsT = log::DefaultLevels, class SubjectsT = log::DefaultSubjects> std::unique_ptr<LogStatusFile> xl::log::Log< LevelsT, SubjectsT >::log_status_file
Definition at line 337 of file log.h.
The documentation for this class was generated from the following file:
include/xl/log/log.h