xl - xaxxon's library: xl::templates::Template Class Reference
xl::templates::Template Class Reference
#include <templates.h>
Public Member Functions
Template (std::string const &tmpl)
Template (std::string &&tmpl="")
char const * c_str () const
template<class ProviderContainer = void, class T = std::string>
std::string fill (T &&source=T{}, ProviderData &&={}) const
void compile () const
bool is_compiled () const
Detailed Description
Definition at line 47 of file templates.h.
Constructor & Destructor Documentation
Template() [1/2]
xl::templates::Template::Template (std::string const & tmpl) inline
Definition at line 61 of file templates.h.
Template() [2/2]
xl::templates::Template::Template (std::string && tmpl = "") inline
Definition at line 62 of file templates.h.
Member Function Documentation
c_str()
char const* xl::templates::Template::c_str () const inline
Definition at line 64 of file templates.h.
Referenced by xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::operator()().
fill()
template<typename ProviderContainer , class T > std::string xl::templates::Template::fill (T && source = T{}, ProviderData && input_data = {}) const
Definition at line 90 of file templates.h.
References xl::templates::ProviderData::contingent_leading_content, xl::templates::ProviderData::contingent_trailing_content, xl::templates::ProviderData::current_template, xl::templates::Provider_Interface::get_name(), xl::templates::ProviderData::inline_template, xl::templates::make_provider(), xl::templates::ProviderData::name, xl::templates::ProviderData::template_name, xl::templates::ProviderData::templates, and XL_TEMPLATE_LOG.
Referenced by xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_range_for_loop_able_v< remove_reference_wrapper_t< T > > &&!std::is_convertible_v< remove_reference_wrapper_t< T >, std::string > &&!is_map_v< remove_reference_wrapper_t< T > > > >::operator()(), and precompiled_template().
compile()
void xl::templates::Template::compile () const inline
Definition at line 205 of file templates.h.
References xl::templates::TemplateSubjects::Compile, xl::templates::ProviderData::contingent_leading_content, xl::DOLLAR_END_ONLY, xl::DOTALL, xl::EXTENDED, xl::templates::ProviderData::ignore_empty_replacements, xl::templates::ProviderData::inline_template, xl::templates::ProviderData::join_string, xl::templates::ProviderData::leading_join_string, xl::templates::log, xl::RegexStd::match(), xl::templates::ProviderData::name, xl::OPTIMIZE, xl::templates::ProviderData::parameters, xl::RegexResultStd::size(), and xl::templates::ProviderData::template_name.
Referenced by precompiled_template().
is_compiled()
bool xl::templates::Template::is_compiled () const inline
Definition at line 200 of file templates.h.
The documentation for this class was generated from the following file:
include/xl/templates/templates.h