xl - xaxxon's library: xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > > Class Template Reference
xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > > Class Template Reference
#include <provider.h>
Public Types
using MapT = remove_refs_and_wrapper_t< T >
using MapKeyT = typename MapT::key_type
using MapValueT = typename MapT::mapped_type
Public Member Functions
template<class... Keys, class... Values>
Provider (std::pair< Keys, Values > &&... pairs)
Provider (T map_holder)
~Provider ()
std::string operator() (ProviderData &data) override
std::string get_name () const override
bool provides_named_lookup () override
ProviderPtr get_named_provider (ProviderData &data) override
Public Attributes
T map_holder
Detailed Description
template<typename ProviderContainer>
template<typename T>
class xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >
Map Provider
Definition at line 506 of file provider.h.
Member Typedef Documentation
MapT
template<typename ProviderContainer> template<typename T > using xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::MapT = remove_refs_and_wrapper_t<T>
Definition at line 509 of file provider.h.
MapKeyT
template<typename ProviderContainer> template<typename T > using xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::MapKeyT = typename MapT::key_type
Definition at line 510 of file provider.h.
MapValueT
template<typename ProviderContainer> template<typename T > using xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::MapValueT = typename MapT::mapped_type
Definition at line 511 of file provider.h.
Constructor & Destructor Documentation
Provider() [1/2]
template<typename ProviderContainer> template<typename T > template<class... Keys, class... Values> xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::Provider (std::pair< Keys, Values > &&... pairs) inline
Definition at line 516 of file provider.h.
References xl::templates::DefaultProviders< ProviderContainer >::make_provider(), and XL_TEMPLATE_LOG.
Provider() [2/2]
template<typename ProviderContainer> template<typename T > xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::Provider (T map_holder) inline
Definition at line 527 of file provider.h.
References XL_TEMPLATE_LOG.
~Provider()
template<typename ProviderContainer> template<typename T > xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::~Provider () inline
Definition at line 540 of file provider.h.
References XL_TEMPLATE_LOG.
Member Function Documentation
operator()()
template<typename ProviderContainer> template<typename T > std::string xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::operator() (ProviderData & data) inline override virtual
Implements xl::templates::Provider_Interface.
Definition at line 545 of file provider.h.
References xl::templates::Template::c_str(), xl::templates::ProviderData::current_template, xl::templates::ProviderData::name, and XL_TEMPLATE_LOG.
get_name()
template<typename ProviderContainer> template<typename T > std::string xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::get_name () const inline override virtual
A string useful for a human to figure out what Provider this is
Returns
Returns a human-readable, useful name for the type of the provider
Implements xl::templates::Provider_Interface.
Definition at line 579 of file provider.h.
provides_named_lookup()
template<typename ProviderContainer> template<typename T > bool xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::provides_named_lookup () inline override virtual
Whether this provider can
Returns
Reimplemented from xl::templates::Provider_Interface.
Definition at line 590 of file provider.h.
get_named_provider()
template<typename ProviderContainer> template<typename T > ProviderPtr xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::get_named_provider (ProviderData & data) inline override virtual
Reimplemented from xl::templates::Provider_Interface.
Definition at line 594 of file provider.h.
References xl::templates::DefaultProviders< ProviderContainer >::make_provider(), and xl::templates::ProviderData::name.
Member Data Documentation
map_holder
template<typename ProviderContainer> template<typename T > T xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::map_holder
Definition at line 513 of file provider.h.
The documentation for this class was generated from the following file:
include/xl/templates/provider.h