xl - xaxxon's library: xl::AlignedStringBuffer_Dynamic< alignment_v > Class Template Reference
xl::AlignedStringBuffer_Dynamic< alignment_v > Class Template Reference
#include <dynamic_buffer.h>
Public Member Functions
AlignedStringBuffer_Dynamic ()=default
void allocate (size_t initial_capacity)
char * buffer ()
auto const buffer () const
char const * c_str ()
auto capacity () const
auto length () const
void concat (char const *source, uint32_t length)
bool empty () const
Static Public Attributes
static constexpr size_t alignment = alignment_v
Detailed Description
template<size_t alignment_v>
class xl::AlignedStringBuffer_Dynamic< alignment_v >
Dynamically-allocated buffer for AlignedString. Buffer will be aligned to the specified alignment and grows in multiples of the alignment
Template Parameters
alignment_v alignment of the dynamically-allocated buffer Must be 16 or 64
Definition at line 37 of file dynamic_buffer.h.
Constructor & Destructor Documentation
AlignedStringBuffer_Dynamic()
template<size_t alignment_v> xl::AlignedStringBuffer_Dynamic< alignment_v >::AlignedStringBuffer_Dynamic () default
Member Function Documentation
allocate()
template<size_t alignment_v> void xl::AlignedStringBuffer_Dynamic< alignment_v >::allocate (size_t initial_capacity) inline
Definition at line 53 of file dynamic_buffer.h.
References xl::AlignedStringBuffer_Dynamic< alignment_v >::buffer(), xl::AlignedStringBuffer_Dynamic< alignment_v >::capacity(), and xl::AlignedStringBuffer_Dynamic< alignment_v >::empty().
Referenced by xl::AlignedStringBuffer_Dynamic< alignment_v >::concat().
buffer() [1/2]
template<size_t alignment_v> char* xl::AlignedStringBuffer_Dynamic< alignment_v >::buffer () inline
Definition at line 67 of file dynamic_buffer.h.
Referenced by xl::AlignedStringBuffer_Dynamic< alignment_v >::allocate(), xl::AlignedStringBuffer_Dynamic< alignment_v >::c_str(), and xl::AlignedStringBuffer_Dynamic< alignment_v >::concat().
buffer() [2/2]
template<size_t alignment_v> auto const xl::AlignedStringBuffer_Dynamic< alignment_v >::buffer () const inline
Definition at line 73 of file dynamic_buffer.h.
References xl::AlignedStringBuffer_Dynamic< alignment_v >::buffer().
Referenced by xl::AlignedStringBuffer_Dynamic< alignment_v >::buffer().
c_str()
template<size_t alignment_v> char const* xl::AlignedStringBuffer_Dynamic< alignment_v >::c_str () inline
Definition at line 76 of file dynamic_buffer.h.
References xl::AlignedStringBuffer_Dynamic< alignment_v >::buffer().
capacity()
template<size_t alignment_v> auto xl::AlignedStringBuffer_Dynamic< alignment_v >::capacity () const inline
Maximum string length which can be held in the current buffer
Returns
Maximum string length which can be held in the current buffer
Definition at line 85 of file dynamic_buffer.h.
Referenced by xl::AlignedStringBuffer_Dynamic< alignment_v >::allocate(), and xl::AlignedStringBuffer_Dynamic< alignment_v >::concat().
length()
template<size_t alignment_v> auto xl::AlignedStringBuffer_Dynamic< alignment_v >::length () const inline
Definition at line 87 of file dynamic_buffer.h.
Referenced by xl::AlignedStringBuffer_Dynamic< alignment_v >::concat().
concat()
template<size_t alignment_v> void xl::AlignedStringBuffer_Dynamic< alignment_v >::concat (char const * source, uint32_t length) inline
Definition at line 89 of file dynamic_buffer.h.
References xl::AlignedStringBuffer_Dynamic< alignment_v >::allocate(), xl::AlignedStringBuffer_Dynamic< alignment_v >::buffer(), xl::AlignedStringBuffer_Dynamic< alignment_v >::capacity(), and xl::AlignedStringBuffer_Dynamic< alignment_v >::length().
empty()
template<size_t alignment_v> bool xl::AlignedStringBuffer_Dynamic< alignment_v >::empty () const inline
Definition at line 97 of file dynamic_buffer.h.
Referenced by xl::AlignedStringBuffer_Dynamic< alignment_v >::allocate().
Member Data Documentation
alignment
template<size_t alignment_v> constexpr size_t xl::AlignedStringBuffer_Dynamic< alignment_v >::alignment = alignment_v static
Definition at line 39 of file dynamic_buffer.h.
The documentation for this class was generated from the following file:
include/xl/aligned_string/dynamic_buffer.h