xl - xaxxon's library: Ui::MainWindow Class Reference
Ui::MainWindow Class Reference
#include <ui_mainwindow.h>
Public Member Functions
void setupUi (QMainWindow *MainWindow)
void retranslateUi (QMainWindow *MainWindow)
Public Attributes
QAction * action_Open
QWidget * centralWidget
QHBoxLayout * horizontalLayout_2
QHBoxLayout * horizontalLayout
QVBoxLayout * verticalLayout
QHBoxLayout * horizontalLayout_4
QCheckBox * allLevels
QLabel * levelLabel
QSpacerItem * horizontalSpacer
QListView * levelList
QVBoxLayout * verticalLayout_2
QHBoxLayout * horizontalLayout_5
QCheckBox * allSubjects
QLabel * subjectLabel
QSpacerItem * horizontalSpacer_2
QListView * subjectList
QStatusBar * statusBar
QMenuBar * menuBar
QMenu * menu_File
Detailed Description
Definition at line 170 of file ui_mainwindow.h.
Member Function Documentation
setupUi()
void Ui_MainWindow::setupUi (QMainWindow * MainWindow) inline inherited
Definition at line 54 of file ui_mainwindow.h.
References Ui_MainWindow::retranslateUi().
Referenced by MainWindow::MainWindow().
retranslateUi()
void Ui_MainWindow::retranslateUi (QMainWindow * MainWindow) inline inherited
Definition at line 156 of file ui_mainwindow.h.
Referenced by Ui_MainWindow::setupUi().
Member Data Documentation
action_Open
QAction* Ui_MainWindow::action_Open inherited
Definition at line 34 of file ui_mainwindow.h.
centralWidget
QWidget* Ui_MainWindow::centralWidget inherited
Definition at line 35 of file ui_mainwindow.h.
horizontalLayout_2
QHBoxLayout* Ui_MainWindow::horizontalLayout_2 inherited
Definition at line 36 of file ui_mainwindow.h.
horizontalLayout
QHBoxLayout* Ui_MainWindow::horizontalLayout inherited
Definition at line 37 of file ui_mainwindow.h.
verticalLayout
QVBoxLayout* Ui_MainWindow::verticalLayout inherited
Definition at line 38 of file ui_mainwindow.h.
horizontalLayout_4
QHBoxLayout* Ui_MainWindow::horizontalLayout_4 inherited
Definition at line 39 of file ui_mainwindow.h.
allLevels
QCheckBox* Ui_MainWindow::allLevels inherited
Definition at line 40 of file ui_mainwindow.h.
levelLabel
QLabel* Ui_MainWindow::levelLabel inherited
Definition at line 41 of file ui_mainwindow.h.
horizontalSpacer
QSpacerItem* Ui_MainWindow::horizontalSpacer inherited
Definition at line 42 of file ui_mainwindow.h.
levelList
QListView* Ui_MainWindow::levelList inherited
Definition at line 43 of file ui_mainwindow.h.
verticalLayout_2
QVBoxLayout* Ui_MainWindow::verticalLayout_2 inherited
Definition at line 44 of file ui_mainwindow.h.
horizontalLayout_5
QHBoxLayout* Ui_MainWindow::horizontalLayout_5 inherited
Definition at line 45 of file ui_mainwindow.h.
allSubjects
QCheckBox* Ui_MainWindow::allSubjects inherited
Definition at line 46 of file ui_mainwindow.h.
subjectLabel
QLabel* Ui_MainWindow::subjectLabel inherited
Definition at line 47 of file ui_mainwindow.h.
horizontalSpacer_2
QSpacerItem* Ui_MainWindow::horizontalSpacer_2 inherited
Definition at line 48 of file ui_mainwindow.h.
subjectList
QListView* Ui_MainWindow::subjectList inherited
Definition at line 49 of file ui_mainwindow.h.
statusBar
QStatusBar* Ui_MainWindow::statusBar inherited
Definition at line 50 of file ui_mainwindow.h.
Referenced by MainWindow::MainWindow().
menuBar
QMenuBar* Ui_MainWindow::menuBar inherited
Definition at line 51 of file ui_mainwindow.h.
menu_File
QMenu* Ui_MainWindow::menu_File inherited
Definition at line 52 of file ui_mainwindow.h.
The documentation for this class was generated from the following file:
cmake-build-debug/log_gui/log_gui_autogen/include/ui_mainwindow.h