xl - xaxxon's library: xl::RegexStd Class Reference
xl::RegexStd Class Reference
#include <regex_std.h>
Public Member Functions
RegexStd (xl::zstring_view regex_string, xl::RegexFlags flags=NONE)
RegexStd (std::regex regex)
RegexResultStd match (std::string_view source) const
std::string replace (xl::zstring_view source, xl::zstring_view result)
Detailed Description
Definition at line 70 of file regex_std.h.
Constructor & Destructor Documentation
RegexStd() [1/2]
xl::RegexStd::RegexStd (xl::zstring_view regex_string, xl::RegexFlags flags = NONE) inline
Definition at line 97 of file regex_std.h.
References xl::basic_zstring_view< CharT, Traits >::c_str().
RegexStd() [2/2]
xl::RegexStd::RegexStd (std::regex regex) inline
Definition at line 109 of file regex_std.h.
Member Function Documentation
match()
RegexResultStd xl::RegexStd::match (std::string_view source) const inline
Definition at line 112 of file regex_std.h.
References xl::RegexResultStd::RegexResultStd().
Referenced by xl::templates::Template::compile(), xl::regexer(), and xl_regex_std_match().
replace()
std::string xl::RegexStd::replace (xl::zstring_view source, xl::zstring_view result) inline
Definition at line 118 of file regex_std.h.
References xl::basic_zstring_view< CharT, Traits >::c_str().
Referenced by xl_std_regex_replace().
The documentation for this class was generated from the following file:
include/xl/regex/regex_std.h