xl - xaxxon's library: xl::magic_ptr< T > Class Template Reference
xl::magic_ptr< T > Class Template Reference
#include <magic_ptr.h>
Public Types
using Deleter = std::function< void(T *)>
Public Member Functions
magic_ptr ()
magic_ptr (T *t, Deleter deleter)
magic_ptr (T &t)
magic_ptr (T &&t)
template<class UniquePtrDeleter >
magic_ptr (std::unique_ptr< T, UniquePtrDeleter > unique_ptr)
magic_ptr (magic_ptr &&other)
magic_ptr (magic_ptr const &)=delete
magic_ptr & operator= (magic_ptr &&other)
magic_ptr & operator= (magic_ptr const &other)=delete
~magic_ptr ()
T * get () const
T & operator* () const
T * release ()
bool empty () const
operator bool () const
T * operator-> ()
Static Public Attributes
static Deleter const noop_deleter = [](T *) {}
static Deleter const default_deleter = [](T * t) { delete t; }
Detailed Description
template<class T>
class xl::magic_ptr< T >
A magic_ptr is similar to a unique_ptr but it knows if it's holding a "reference" or an owning pointer based on whether it was created with an rvalue or lvalue reference. Both kinds of magic_ptr's have the same type, however, so they can be used interchangeably in a homogenous container magic_ptr's are move-only like a unique_ptr, as they may own memory. Note: magic_ptr's are HUGE, likely 5x a normal pointer. Use with care.
Definition at line 31 of file magic_ptr.h.
Member Typedef Documentation
Deleter
template<class T > using xl::magic_ptr< T >::Deleter = std::function<void(T *)>
Definition at line 33 of file magic_ptr.h.
Constructor & Destructor Documentation
magic_ptr() [1/7]
template<class T > xl::magic_ptr< T >::magic_ptr () inline
Constructs empty object
Definition at line 57 of file magic_ptr.h.
magic_ptr() [2/7]
template<class T > xl::magic_ptr< T >::magic_ptr (T * t, Deleter deleter) inline
Takes a pointer to an object and a deleter Caller must specify the deleter because it can't otherwise be known if the object should be "owned" or not
Parameters
t pointer to object
deleter
Definition at line 68 of file magic_ptr.h.
magic_ptr() [3/7]
template<class T > xl::magic_ptr< T >::magic_ptr (T & t) inline
Non-owning constructor for existing T objects
Parameters
t
Definition at line 78 of file magic_ptr.h.
magic_ptr() [4/7]
template<class T > xl::magic_ptr< T >::magic_ptr (T && t) inline
Owning constructor calls move constructor for type T
Parameters
t object to move out of
Definition at line 87 of file magic_ptr.h.
magic_ptr() [5/7]
template<class T > template<class UniquePtrDeleter > xl::magic_ptr< T >::magic_ptr (std::unique_ptr< T, UniquePtrDeleter > unique_ptr) inline
Owning constructor which takes ownership from unique_ptr and uses the unique_ptr's deleter as well. Empty unique_ptr's are fine
Template Parameters
UniquePtrDeleter the Deleter type of the unique_ptr
Parameters
unique_ptr unique_ptr from which to transfer object ownership
Definition at line 100 of file magic_ptr.h.
magic_ptr() [6/7]
template<class T > xl::magic_ptr< T >::magic_ptr (magic_ptr< T > && other) inline
Move constructor for magic_ptr
Parameters
other
Definition at line 109 of file magic_ptr.h.
References xl::magic_ptr(), and xl::magic_ptr< T >::noop_deleter.
magic_ptr() [7/7]
template<class T > xl::magic_ptr< T >::magic_ptr (magic_ptr< T > const &) delete
~magic_ptr()
template<class T > xl::magic_ptr< T >::~magic_ptr () inline
Definition at line 140 of file magic_ptr.h.
Member Function Documentation
operator=() [1/2]
template<class T > magic_ptr& xl::magic_ptr< T >::operator= (magic_ptr< T > && other) inline
Move assignment operator for magic_ptr
Parameters
other
Returns
Definition at line 124 of file magic_ptr.h.
References xl::magic_ptr< T >::noop_deleter.
operator=() [2/2]
template<class T > magic_ptr& xl::magic_ptr< T >::operator= (magic_ptr< T > const & other) delete
get()
template<class T > T* xl::magic_ptr< T >::get () const inline
Returns the pointer to the contained object, or nullptr if none
Returns
Definition at line 148 of file magic_ptr.h.
operator*()
template<class T > T& xl::magic_ptr< T >::operator* () const inline
Returns reference to the contained object
Returns
Exceptions
magic_ptr_exception if magic_ptr is empty
Definition at line 157 of file magic_ptr.h.
References xl::magic_ptr_exception::magic_ptr_exception().
release()
template<class T > T* xl::magic_ptr< T >::release () inline
Calls deleter (which may do nothing) on contained object and then becomes empty
Returns
Definition at line 169 of file magic_ptr.h.
References xl::magic_ptr< T >::noop_deleter.
empty()
template<class T > bool xl::magic_ptr< T >::empty () const inline
Definition at line 178 of file magic_ptr.h.
operator bool()
template<class T > xl::magic_ptr< T >::operator bool () const inline
Definition at line 182 of file magic_ptr.h.
operator->()
template<class T > T* xl::magic_ptr< T >::operator-> () inline
Definition at line 186 of file magic_ptr.h.
References xl::magic_ptr().
Member Data Documentation
noop_deleter
template<class T > Deleter const xl::magic_ptr< T >::noop_deleter = [](T *) {} inline static
Deleter which does nothing, for non-owning magic_ptr's
Definition at line 44 of file magic_ptr.h.
Referenced by xl::magic_ptr< T >::magic_ptr(), xl::magic_ptr< T >::operator=(), and xl::magic_ptr< T >::release().
default_deleter
template<class T > Deleter const xl::magic_ptr< T >::default_deleter = [](T * t) { delete t; } inline static
Deleter which calls delete on the object, for owning magic_ptr's
Definition at line 50 of file magic_ptr.h.
The documentation for this class was generated from the following file:
include/xl/magic_ptr.h