xl - xaxxon's library: xl::basic_zstring_view< CharT, Traits > Class Template Reference
xl::basic_zstring_view< CharT, Traits > Class Template Reference
#include <zstring_view.h>
Public Member Functions
basic_zstring_view (std::basic_string< CharT > const &source)
CharT const * c_str () const
operator std::basic_string< CharT > () const
Detailed Description
template<class CharT, class Traits = std::char_traits<CharT>>
class xl::basic_zstring_view< CharT, Traits >
basic_zstring_view is a std::basic_string_view that is guaranteed to be null terminated. adds c_str() as a synonym for std::string_view::data to make it clear that it is null terminated like it is in std::string::c_str()
Definition at line 15 of file zstring_view.h.
Constructor & Destructor Documentation
basic_zstring_view()
template<class CharT , class Traits = std::char_traits<CharT>> xl::basic_zstring_view< CharT, Traits >::basic_zstring_view (std::basic_string< CharT > const & source) inline
Definition at line 20 of file zstring_view.h.
Member Function Documentation
c_str()
template<class CharT , class Traits = std::char_traits<CharT>> CharT const* xl::basic_zstring_view< CharT, Traits >::c_str () const inline
Definition at line 27 of file zstring_view.h.
Referenced by xl::log::Log< LevelsT, SubjectsT >::log(), xl::RegexStd::RegexStd(), and xl::RegexStd::replace().
operator std::basic_string< CharT >()
template<class CharT , class Traits = std::char_traits<CharT>> xl::basic_zstring_view< CharT, Traits >::operator std::basic_string< CharT > () const inline
Definition at line 29 of file zstring_view.h.
The documentation for this class was generated from the following file:
include/xl/zstring_view.h