xl - xaxxon's library: xl::AlignedStringBuffer_Static< size > Class Template Reference
xl::AlignedStringBuffer_Static< size > Class Template Reference
#include <static_buffer.h>
Public Member Functions
length_t length () const
void allocate (size_t new_size) const
AlignedStringBuffer_Static ()
AlignedStringBuffer_Static (AlignedStringBuffer_Static &&other)
char * buffer ()
char const * buffer () const
char const * c_str ()
auto capacity () const
void concat (char const *source, uint32_t length)
bool empty () const
Static Public Attributes
static constexpr size_t alignment = size % 64 == 0 ? 64 : 16
Detailed Description
template<size_t size>
class xl::AlignedStringBuffer_Static< size >
An inline storage buffer for AlignedString which uses a fixed-length array for storage
Allows storage of a string of length size-1 and then a NUL terminator
Uses the last byte to store a representation of the length in such a way that the value is 0 when the string is full and therefor doubles as the NUL terminator
Template Parameters
size maximum amount of size the entire object can use, including any overhead
Definition at line 15 of file static_buffer.h.
Constructor & Destructor Documentation
AlignedStringBuffer_Static() [1/2]
template<size_t size> xl::AlignedStringBuffer_Static< size >::AlignedStringBuffer_Static () inline
Definition at line 55 of file static_buffer.h.
AlignedStringBuffer_Static() [2/2]
template<size_t size> xl::AlignedStringBuffer_Static< size >::AlignedStringBuffer_Static (AlignedStringBuffer_Static< size > && other) inline
Definition at line 60 of file static_buffer.h.
Member Function Documentation
length()
template<size_t size> length_t xl::AlignedStringBuffer_Static< size >::length () const inline
Definition at line 37 of file static_buffer.h.
Referenced by xl::AlignedStringBuffer_Static< size >::concat().
allocate()
template<size_t size> void xl::AlignedStringBuffer_Static< size >::allocate (size_t new_size) const inline
Doesn't do anything because the size of the buffer is fixed at compile time, but will throw an exception if the requested size is larger than the static size
Parameters
new_size
Definition at line 48 of file static_buffer.h.
buffer() [1/2]
template<size_t size> char* xl::AlignedStringBuffer_Static< size >::buffer () inline
Returns the raw string buffer
Returns
the raw string buffer
Definition at line 71 of file static_buffer.h.
Referenced by xl::AlignedStringBuffer_Static< size >::c_str(), and xl::AlignedStringBuffer_Static< size >::concat().
buffer() [2/2]
template<size_t size> char const* xl::AlignedStringBuffer_Static< size >::buffer () const inline
Definition at line 72 of file static_buffer.h.
References xl::AlignedStringBuffer_Static< size >::buffer().
Referenced by xl::AlignedStringBuffer_Static< size >::buffer().
c_str()
template<size_t size> char const* xl::AlignedStringBuffer_Static< size >::c_str () inline
Definition at line 75 of file static_buffer.h.
References xl::AlignedStringBuffer_Static< size >::buffer().
capacity()
template<size_t size> auto xl::AlignedStringBuffer_Static< size >::capacity () const inline
Returns the current maximum length of a string of the buffer
Returns
the current maximum length of a string of the buffer
Definition at line 83 of file static_buffer.h.
concat()
template<size_t size> void xl::AlignedStringBuffer_Static< size >::concat (char const * source, uint32_t length) inline
Adds the specified string to the current string
Parameters
source raw source buffer
length number of bytes to concat into this buffer
Definition at line 91 of file static_buffer.h.
References xl::AlignedStringBuffer_Static< size >::buffer(), and xl::AlignedStringBuffer_Static< size >::length().
empty()
template<size_t size> bool xl::AlignedStringBuffer_Static< size >::empty () const inline
Definition at line 100 of file static_buffer.h.
Member Data Documentation
alignment
template<size_t size> constexpr size_t xl::AlignedStringBuffer_Static< size >::alignment = size % 64 == 0 ? 64 : 16 static
Definition at line 24 of file static_buffer.h.
The documentation for this class was generated from the following file:
include/xl/aligned_string/static_buffer.h