xl - xaxxon's library: xl::log::LogStatusFile Class Reference
xl::log::LogStatusFile Class Reference
#include <log.h>
Public Member Functions
template<typename LevelsT , typename SubjectsT >
LogStatusFile (Log< LevelsT, SubjectsT > const &log, std::string filename, bool force_reset)
template<typename LevelsT , typename SubjectsT >
void initialize_from_log (Log< LevelsT, SubjectsT > const &log)
LogStatusFile (std::string filename)
void read ()
template<typename LevelsT , typename SubjectsT >
void write (Log< LevelsT, SubjectsT > const &log)
void write ()
bool check ()
Public Attributes
std::vector< std::pair< std::string, bool > > level_names
std::vector< std::pair< std::string, bool > > subject_names
Detailed Description
Definition at line 118 of file log.h.
Constructor & Destructor Documentation
LogStatusFile() [1/2]
template<typename LevelsT , typename SubjectsT > xl::log::LogStatusFile::LogStatusFile (Log< LevelsT, SubjectsT > const & log, std::string filename, bool force_reset) inline
Definition at line 137 of file log.h.
LogStatusFile() [2/2]
xl::log::LogStatusFile::LogStatusFile (std::string filename) inline
Definition at line 166 of file log.h.
Member Function Documentation
initialize_from_log()
template<typename LevelsT , typename SubjectsT > void xl::log::LogStatusFile::initialize_from_log (Log< LevelsT, SubjectsT > const & log) inline
Definition at line 151 of file log.h.
References xl::log::Log< LevelsT, SubjectsT >::get_level_status(), xl::log::Log< LevelsT, SubjectsT >::get_subject_status(), and std::__1::pair().
read()
void xl::log::LogStatusFile::read () inline
Definition at line 171 of file log.h.
References std::__1::pair().
write() [1/2]
template<typename LevelsT , typename SubjectsT > void xl::log::LogStatusFile::write (Log< LevelsT, SubjectsT > const & log) inline
Definition at line 218 of file log.h.
write() [2/2]
void xl::log::LogStatusFile::write () inline
Definition at line 224 of file log.h.
check()
bool xl::log::LogStatusFile::check () inline
Definition at line 246 of file log.h.
Member Data Documentation
level_names
std::vector<std::pair<std::string, bool> > xl::log::LogStatusFile::level_names
Definition at line 132 of file log.h.
subject_names
std::vector<std::pair<std::string, bool> > xl::log::LogStatusFile::subject_names
Definition at line 133 of file log.h.
The documentation for this class was generated from the following file:
include/xl/log/log.h