xl - xaxxon's library: xl::templates Namespace Reference
xl::templates Namespace Reference
Classes
struct DefaultProviders
class EmptyProvider
struct is_passthrough_provider
struct is_passthrough_provider< T, std::enable_if_t< std::is_same_v< void, std::void_t< typename std::decay_t< T >::XL_TEMPLATES_PASSTHROUGH_TYPE > > > >
class Provider_Interface
struct ProviderData
class Template
class TemplateException
struct TemplateSubjects
Typedefs
using TemplateMap = std::map< std::string, Template >
using ProviderPtr = std::unique_ptr< Provider_Interface >
using LogT = ::xl::log::Log<::xl::log::DefaultLevels, TemplateSubjects >
Functions
template<class CharT , class Traits >
Template load_template_from_istream (std::basic_istream< CharT, Traits > const &istream)
std::string make_template_name (std::string const &filename)
TemplateMap load_templates (std::string_view path_name)
template<typename ProviderContainer = void, typename... Ts>
ProviderPtr make_provider (Ts &&... ts)
Variables
template<class T >
constexpr bool is_passthrough_provider_v = is_passthrough_provider<T>::value
LogT log
Typedef Documentation
TemplateMap
typedef std::map< std::string, Template > xl::templates::TemplateMap
Definition at line 13 of file provider_data.h.
ProviderPtr
using xl::templates::ProviderPtr = typedef std::unique_ptr<Provider_Interface>
Definition at line 12 of file provider_interface.h.
LogT
using xl::templates::LogT = typedef ::xl::log::Log<::xl::log::DefaultLevels, TemplateSubjects>
Definition at line 40 of file templates.h.
Function Documentation
load_template_from_istream()
template<class CharT , class Traits > Template xl::templates::load_template_from_istream (std::basic_istream< CharT, Traits > const & istream)
Definition at line 18 of file directory_loader.h.
Referenced by load_templates().
make_template_name()
std::string xl::templates::make_template_name (std::string const & filename) inline
Definition at line 30 of file directory_loader.h.
Referenced by load_templates().
load_templates()
TemplateMap xl::templates::load_templates (std::string_view path_name) inline
Loads either a single file or a directory of files into a std::map appropriate for sending to Template::fill If the filename ends with .template, the trailing .template is removed from the key in the returned map
Parameters
path_name file or directory name
Returns
map of templates with keys being just the filename (not the full path) of the files loaded
Definition at line 42 of file directory_loader.h.
References load_template_from_istream(), and make_template_name().
make_provider()
template<typename ProviderContainer = void, typename... Ts> ProviderPtr xl::templates::make_provider (Ts &&... ts)
Definition at line 623 of file provider.h.
References xl::templates::DefaultProviders< ProviderContainer >::make_provider().
Referenced by xl::templates::Template::fill().
Variable Documentation
is_passthrough_provider_v
template<class T > constexpr bool xl::templates::is_passthrough_provider_v = is_passthrough_provider<T>::value
Definition at line 58 of file provider_interface.h.
Referenced by xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::unique_ptr, remove_reference_wrapper_t< T > > > >::get_name().
log
LogT xl::templates::log inline
Definition at line 41 of file templates.h.
Referenced by xl::templates::Template::compile(), and xl::log::Log< LevelsT, SubjectsT >::log().