xl - xaxxon's library: xl Namespace Reference
xl Namespace Reference
Namespaces
log
templates
Classes
struct _is_template_for
struct _is_template_for< tmpl, tmpl< Args... > >
class AlignedString
class AlignedStringBuffer_Dynamic
class AlignedStringBuffer_Static
class AlignedStringException
class basic_string_view
class basic_zstring_view
class CloneableUniquePtr
class CloneableUniquePtr< T, std::enable_if_t< std::is_same_v< std::result_of_t< decltype(&T::clone)(T)>, T * > > >
struct declval< T >()))>>
struct declval< T >()))>>
class EAC
class EAC< Return(Class::*)(T)>
class EAC< T >
struct EachI
struct EachI< std::index_sequence< Is... >, Containers... >
struct FilteredInsertIterator
class FormattedException
struct has_find_for
struct has_insertion_operator
struct is_map
struct is_pair
struct is_range_for_loop_able
class magic_ptr
class magic_ptr_exception
struct make_reference_wrapper
struct make_reference_wrapper< std::reference_wrapper< T > >
struct map_for_pair
struct map_for_pair< std::pair< T1, T2 >, Args... >
struct match_const_of
class RegexException
class RegexResultStd
class RegexStd
struct remove_reference_wrapper
Typedefs
template<class T >
using unique_ptr_type = _unique_ptr_type< std::decay_t< T > >
template<class T >
using unique_ptr_type_t = typename unique_ptr_type< T >::type
template<template< class... > class tmpl, typename... Ts>
using is_template_for = std::conjunction< _is_template_for< tmpl, std::decay_t< Ts > >... >
template<typename... Ts>
using map_for_pair_t = typename map_for_pair< Ts... >::type
template<class... >
using int_t = int
template<typename T >
using remove_reference_wrapper_t = typename remove_reference_wrapper< T >::type
template<class T >
using remove_refs_and_wrapper = remove_reference_wrapper< std::remove_reference_t< T > >
template<class T >
using remove_refs_and_wrapper_t = typename remove_refs_and_wrapper< T >::type
template<class T , class U >
using match_const_of_t = typename match_const_of< T, U >::type
template<class T >
using make_reference_wrapper_t = typename make_reference_wrapper< T >::type
template<typename T >
using is_std_array = _is_std_array< std::decay_t< T > >
using RegexFlagsT = std::underlying_type_t< RegexFlags >
using Regex = xl::RegexStd
using zstring_view = basic_zstring_view< char >
using wzstring_view = basic_zstring_view< wchar_t >
using u16zstring_view = basic_zstring_view< char16_t >
using u32zstring_view = basic_zstring_view< char32_t >
using string_view = basic_string_view< char >
using wstring_view = basic_string_view< wchar_t >
using u16string_view = basic_string_view< char16_t >
using u32string_view = basic_string_view< char32_t >
Enumerations
enum RegexFlags {
NONE = 0, OPTIMIZE = 1 << 0, ICASE = 1 << 1, EXTENDED = 1 << 2,
DOTALL = 1 << 3, MULTILINE = 1 << 4, DOLLAR_END_ONLY = 1 << 5
}
Functions
template<class AlignedStringBuffer_t >
std::ostream & operator<< (std::ostream &os, AlignedString< AlignedStringBuffer_t > const &aligned_string)
template<size_t alignment>
std::unique_ptr< char[]> allocate_aligned_blocks (size_t &minimum_bytes)
template<class T , class... Args>
auto make_cloneable_unique_ptr (Args &&... args)
std::string demangle_typeid_name (const std::string &mangled_name)
template<class T >
std::string & demangle ()
template<typename C , typename V , std::enable_if_t< has_find_for_v< C, V >> * = nullptr>
bool contains (C &&container, V &&value)
template<class ValueT , class... Rest, template< class, class... > class ContainerT>
auto find (ContainerT< ValueT, Rest... > const &container, ValueT const &value)
template<class Container , class Callback >
auto copy_if (Container const &container, Callback &&callback)
template<class... Containers>
auto each_i (Containers &&... containers)
template<class ValueT , class... Rest, template< class, class... > class ContainerT, class Callable >
ContainerT< ValueT, Rest... > remove_copy_if (ContainerT< ValueT, Rest... > const &container, Callable callable)
template<class ValueT , class... Rest, template< class, class... > class ContainerT, class Callable >
ContainerT< std::result_of_t< Callable(ValueT)> > transform (ContainerT< ValueT, Rest... > const &container, Callable callable)
template<class ValueT , class... Rest, template< class, class... > class ContainerT, class Callable , std::enable_if_t< is_template_for_v< std::optional, std::result_of_t< Callable(ValueT)>>, int > = 0>
auto transform_if (ContainerT< ValueT, Rest... > const &container, Callable callable)
template<typename T >
auto get_pointer (T &&t)
template<class T , class Callable , int_t< decltype(std::remove_if(begin(std::declval< T >()), end(std::declval< T >()), std::declval< Callable >()))> = 0>
auto & erase_if (T &container, Callable callable)
template<class T , class Callable , int_t< decltype(std::remove_if(begin(std::declval< T >()), end(std::declval< T >()), std::declval< Callable >()))> = 0>
auto && erase_if (T &&container, Callable callable)
template<class T , std::enable_if_t< std::is_copy_constructible_v< T >, int > = 0>
T copy (T const &t)
template<class ValueT , class... Rest, template< class, class... > class ContainerT>
auto copy (ContainerT< ValueT, Rest... > const &container)
template<class T , class Return , class Class >
auto eac (Return(Class::*pointer)(T))
template<class T >
auto eac (T t)
template<typename T >
FilteredInsertIterator< T > filtered_inserter (typename FilteredInsertIterator< T >::filter_type filter, T &container, typename T::iterator iterator)
template<class T1 , class T2 >
auto forward_as_pair (T1 &&t1, T2 &&t2)
same as forward_as_tuple but for pair
template<class T >
std::string join (T const &container, std::string_view join_string=", ")
template<class T >
magic_ptr (T &) -> magic_ptr< T >
template<class T , class... Args>
magic_ptr< T > make_magic (Args &&... args)
auto regexer (zstring_view string, Regex const &regex)
auto regexer (zstring_view string, zstring_view regex_string)
Regex operator"" _re (char const *regex_string, unsigned long length)
Regex operator"" _rei (char const *regex_string, unsigned long)
Variables
template<class T >
constexpr bool has_insertion_operator_v = has_insertion_operator<T>::value
template<typename T , typename V >
constexpr bool has_find_for_v = has_find_for<T, V>::value
template<template< class... > class tmpl, typename... Ts>
constexpr bool is_template_for_v = is_template_for<tmpl, Ts...>::value
template<typename T >
constexpr bool is_map_v = is_map<T>::value
template<typename T >
constexpr bool is_pair_v = is_pair<T>::value
template<class T >
constexpr bool is_range_for_loop_able_v = is_range_for_loop_able<T>::value
template<typename T >
constexpr bool is_std_array_v = is_std_array<T>::value
Class Documentation
xl::CloneableUniquePtr
class xl::CloneableUniquePtr
template<class T, class = void>
class xl::CloneableUniquePtr< T, class >
Instantiating this type is an error caused by specifying a type that does not implement clone()
Template Parameters
T
Definition at line 13 of file cloneable_unique_pointer.h.
xl::EAC
class xl::EAC
template<class, class = void>
class xl::EAC< class, class >
Definition at line 374 of file library_extensions.h.
xl::EachI
struct xl::EachI
template<class, class...>
struct xl::EachI< class,... >
Takes a container and produces tuples with each value of the container and an associated counter
Definition at line 176 of file library_extensions.h.
xl::make_reference_wrapper
struct xl::make_reference_wrapper
template<class T>
struct xl::make_reference_wrapper< T >
Definition at line 557 of file library_extensions.h.
Class Members
typedef reference_wrapper< T > type
xl::make_reference_wrapper< std::reference_wrapper< T > >
struct xl::make_reference_wrapper< std::reference_wrapper< T > >
template<class T>
struct xl::make_reference_wrapper< std::reference_wrapper< T > >
Definition at line 562 of file library_extensions.h.
Class Members
typedef reference_wrapper< T > type
xl::map_for_pair
struct xl::map_for_pair
template<typename... Ts>
struct xl::map_for_pair< Ts >
Definition at line 124 of file library_extensions.h.
xl::map_for_pair< std::pair< T1, T2 >, Args... >
struct xl::map_for_pair< std::pair< T1, T2 >, Args... >
template<typename T1, typename T2, typename... Args>
struct xl::map_for_pair< std::pair< T1, T2 >, Args... >
Definition at line 127 of file library_extensions.h.
Class Members
typedef map< string, T2 > type
xl::match_const_of
struct xl::match_const_of
template<class T, class U>
struct xl::match_const_of< T, U >
Definition at line 548 of file library_extensions.h.
Class Members
typedef conditional_t
< is_const_v
< remove_reference_t< U >
>, const T, T > type
xl::remove_reference_wrapper
struct xl::remove_reference_wrapper
template<typename T, typename = void>
struct xl::remove_reference_wrapper< T, typename >
type trait removing std::reference_wrapper from around a type, if present
Definition at line 508 of file library_extensions.h.
Class Members
typedef T type
Typedef Documentation
unique_ptr_type
template<class T > using xl::unique_ptr_type = typedef _unique_ptr_type<std::decay_t<T> >
Type trait for the type a unique_ptr points to
Definition at line 70 of file library_extensions.h.
unique_ptr_type_t
template<class T > using xl::unique_ptr_type_t = typedef typename unique_ptr_type<T>::type
The type a unique_ptr points to
Definition at line 76 of file library_extensions.h.
is_template_for
template<template< class... > class tmpl, typename... Ts> using xl::is_template_for = typedef std::conjunction<_is_template_for<tmpl, std::decay_t<Ts> >...>
Definition at line 100 of file library_extensions.h.
map_for_pair_t
template<typename... Ts> using xl::map_for_pair_t = typedef typename map_for_pair<Ts...>::type
Definition at line 132 of file library_extensions.h.
int_t
template<class... > using xl::int_t = typedef int
Definition at line 232 of file library_extensions.h.
remove_reference_wrapper_t
template<typename T > using xl::remove_reference_wrapper_t = typedef typename remove_reference_wrapper<T>::type
The type with std::reference_wrapper removed, if present
Definition at line 517 of file library_extensions.h.
remove_refs_and_wrapper
template<class T > using xl::remove_refs_and_wrapper = typedef remove_reference_wrapper<std::remove_reference_t<T> >
Definition at line 539 of file library_extensions.h.
remove_refs_and_wrapper_t
template<class T > using xl::remove_refs_and_wrapper_t = typedef typename remove_refs_and_wrapper<T>::type
Definition at line 542 of file library_extensions.h.
match_const_of_t
template<class T , class U > using xl::match_const_of_t = typedef typename match_const_of<T, U>::type
Definition at line 553 of file library_extensions.h.
make_reference_wrapper_t
template<class T > using xl::make_reference_wrapper_t = typedef typename make_reference_wrapper<T>::type
Definition at line 567 of file library_extensions.h.
is_std_array
template<typename T > using xl::is_std_array = typedef _is_std_array<std::decay_t<T> >
Test
Definition at line 605 of file library_extensions.h.
RegexFlagsT
using xl::RegexFlagsT = typedef std::underlying_type_t<RegexFlags>
Definition at line 16 of file regexer.h.
Regex
using xl::Regex = typedef xl::RegexStd
Definition at line 51 of file regexer.h.
zstring_view
using xl::zstring_view = typedef basic_zstring_view<char>
Definition at line 32 of file zstring_view.h.
wzstring_view
using xl::wzstring_view = typedef basic_zstring_view<wchar_t>
Definition at line 33 of file zstring_view.h.
u16zstring_view
using xl::u16zstring_view = typedef basic_zstring_view<char16_t>
Definition at line 34 of file zstring_view.h.
u32zstring_view
using xl::u32zstring_view = typedef basic_zstring_view<char32_t>
Definition at line 35 of file zstring_view.h.
string_view
using xl::string_view = typedef basic_string_view<char>
Definition at line 50 of file zstring_view.h.
wstring_view
using xl::wstring_view = typedef basic_string_view<wchar_t>
Definition at line 51 of file zstring_view.h.
u16string_view
using xl::u16string_view = typedef basic_string_view<char16_t>
Definition at line 52 of file zstring_view.h.
u32string_view
using xl::u32string_view = typedef basic_string_view<char32_t>
Definition at line 53 of file zstring_view.h.
Enumeration Type Documentation
RegexFlags
enum xl::RegexFlags
Enumerator
NONE
OPTIMIZE
ICASE
EXTENDED
DOTALL
MULTILINE
DOLLAR_END_ONLY
Definition at line 7 of file regexer.h.
Function Documentation
operator<<()
template<class AlignedStringBuffer_t > std::ostream& xl::operator<< (std::ostream & os, AlignedString< AlignedStringBuffer_t > const & aligned_string)
Definition at line 422 of file aligned_string.h.
allocate_aligned_blocks()
template<size_t alignment> std::unique_ptr<char[]> xl::allocate_aligned_blocks (size_t & minimum_bytes) inline
Allocates an aligned block of at least the requested size
Template Parameters
alignment required alignment of allocated block
Parameters
minimum_bytes in: minimum size out: actual size
Returns
newly allocated buffer
Definition at line 17 of file dynamic_buffer.h.
make_cloneable_unique_ptr()
template<class T , class... Args> auto xl::make_cloneable_unique_ptr (Args &&... args)
Definition at line 99 of file cloneable_unique_pointer.h.
demangle_typeid_name()
std::string xl::demangle_typeid_name (const std::string & mangled_name) inline
Returns a demangled version of the typeid(T).name() passed in if it knows how, otherwise returns the mangled name exactly as passed in
Definition at line 19 of file demangle.h.
Referenced by demangle().
demangle()
template<class T > std::string& xl::demangle ()
Definition at line 53 of file demangle.h.
References demangle_typeid_name().
contains()
template<typename C , typename V , std::enable_if_t< has_find_for_v< C, V >> * = nullptr> bool xl::contains (C && container, V && value)
returns whether the container contains the specified value
Template Parameters
C Container type to look in
V Value type to look for
Parameters
container container to be searched
value value to search the container for
Returns
whether the container contains the specified value
Definition at line 144 of file library_extensions.h.
find()
template<class ValueT , class... Rest, template< class, class... > class ContainerT> auto xl::find (ContainerT< ValueT, Rest... > const & container, ValueT const & value)
Definition at line 156 of file library_extensions.h.
copy_if()
template<class Container , class Callback > auto xl::copy_if (Container const & container, Callback && callback)
Definition at line 161 of file library_extensions.h.
each_i()
template<class... Containers> auto xl::each_i (Containers &&... containers)
Definition at line 226 of file library_extensions.h.
remove_copy_if()
template<class ValueT , class... Rest, template< class, class... > class ContainerT, class Callable > ContainerT<ValueT, Rest...> xl::remove_copy_if (ContainerT< ValueT, Rest... > const & container, Callable callable)
Returns a container only containing elements of the original array which return false when sent to the callback
Template Parameters
ValueT Value type of each element to be processed
Rest
ContainerT
Callable
Parameters
container
callable callback used to determine whether put an element in the output container or not
Returns
container a copy of the containercontaining all the elements of the source container unless the callback returns true for a given element
Definition at line 261 of file library_extensions.h.
transform()
template<class ValueT , class... Rest, template< class, class... > class ContainerT, class Callable > ContainerT<std::result_of_t<Callable(ValueT)> > xl::transform (ContainerT< ValueT, Rest... > const & container, Callable callable)
Takes a container and returns a container of the type returned by running each element through the specified callback
Template Parameters
ValueT Source value type of container
Rest Any additional template parameters on the source container type
ContainerT Container template
Callable Callback type
Parameters
container source container
callable each element of the input container is sent to this callback to populate the returned container
Returns
vector containing result of sending each element of the source container to the callback
Definition at line 277 of file library_extensions.h.
transform_if()
template<class ValueT , class... Rest, template< class, class... > class ContainerT, class Callable , std::enable_if_t< is_template_for_v< std::optional, std::result_of_t< Callable(ValueT)>>, int > = 0> auto xl::transform_if (ContainerT< ValueT, Rest... > const & container, Callable callable)
Given an input container of type Container<T> and a Callable returing std::optional<U>, returns a container Container<U> containing only the elements which weren't an empty std::optional.
Returns
container of non-empty results from callable
Definition at line 294 of file library_extensions.h.
get_pointer()
template<typename T > auto xl::get_pointer (T && t)
Definition at line 308 of file library_extensions.h.
erase_if() [1/2]
template<class T , class Callable , int_t< decltype(std::remove_if(begin(std::declval< T >()), end(std::declval< T >()), std::declval< Callable >()))> = 0> auto& xl::erase_if (T & container, Callable callable)
Similar to std::remove_if but the rejected elements are removed from the container
Template Parameters
T
Callable
Parameters
container
callable
Returns
same container passed in but without the rejected elements
Definition at line 333 of file library_extensions.h.
Referenced by erase_if().
erase_if() [2/2]
template<class T , class Callable , int_t< decltype(std::remove_if(begin(std::declval< T >()), end(std::declval< T >()), std::declval< Callable >()))> = 0> auto&& xl::erase_if (T && container, Callable callable)
Definition at line 340 of file library_extensions.h.
References erase_if().
copy() [1/2]
template<class T , std::enable_if_t< std::is_copy_constructible_v< T >, int > = 0> T xl::copy (T const & t)
If the type is copyable, returns a copy of it
Definition at line 350 of file library_extensions.h.
copy() [2/2]
template<class ValueT , class... Rest, template< class, class... > class ContainerT> auto xl::copy (ContainerT< ValueT, Rest... > const & container)
If it's a container of things that aren't copyable, return a new container of reference (wrappers) to the elements of the original container
Returns
new container with reference_wrapper's to the objects in the original container
Definition at line 360 of file library_extensions.h.
eac() [1/2]
template<class T , class Return , class Class > auto xl::eac (Return(Class::*)(T) pointer)
Definition at line 422 of file library_extensions.h.
eac() [2/2]
template<class T > auto xl::eac (T t)
Definition at line 427 of file library_extensions.h.
filtered_inserter()
template<typename T > FilteredInsertIterator<T> xl::filtered_inserter (typename FilteredInsertIterator< T >::filter_type filter, T & container, typename T::iterator iterator)
Definition at line 482 of file library_extensions.h.
forward_as_pair()
template<class T1 , class T2 > auto xl::forward_as_pair (T1 && t1, T2 && t2)
same as forward_as_tuple but for pair
Definition at line 496 of file library_extensions.h.
join()
template<class T > std::string xl::join (T const & container, std::string_view join_string = ", ")
Joins together the elements of the container with the specified join string between them
Parameters
container
join_string
Returns
string of all the elements combined
Definition at line 577 of file library_extensions.h.
magic_ptr()
template<class T > xl::magic_ptr (T &) -> magic_ptr< T >
Referenced by xl::magic_ptr< T >::magic_ptr(), and xl::magic_ptr< T >::operator->().
make_magic()
template<class T , class... Args> magic_ptr<T> xl::make_magic (Args &&... args)
Definition at line 199 of file magic_ptr.h.
regexer() [1/2]
auto xl::regexer (zstring_view string, Regex const & regex) inline
Definition at line 55 of file regexer.h.
References xl::RegexStd::match().
Referenced by regexer().
regexer() [2/2]
auto xl::regexer (zstring_view string, zstring_view regex_string) inline
Definition at line 60 of file regexer.h.
References regexer().
operator"" _re()
Regex xl::operator"" _re (char const * regex_string, unsigned long length) inline
Definition at line 66 of file regexer.h.
operator"" _rei()
Regex xl::operator"" _rei (char const * regex_string, unsigned long) inline
Definition at line 71 of file regexer.h.
References ICASE.
Variable Documentation
has_insertion_operator_v
template<class T > constexpr bool xl::has_insertion_operator_v = has_insertion_operator<T>::value
LibC++ with clang5 doesn't work with this code - reports true when it should be false for newly created user-defined type: class A{}; has_insertion_operator_v <== true but should be false https://bugs.llvm.org/show_bug.cgi?id=35063
Template Parameters
T Type to check for operator<<
Definition at line 44 of file library_extensions.h.
has_find_for_v
template<typename T , typename V > constexpr bool xl::has_find_for_v = has_find_for<T, V>::value
Whether type T has a member function find which can take a type V
Template Parameters
T Container type
V Type to find
Definition at line 84 of file library_extensions.h.
is_template_for_v
template<template< class... > class tmpl, typename... Ts> constexpr bool xl::is_template_for_v = is_template_for<tmpl, Ts...>::value
Definition at line 103 of file library_extensions.h.
is_map_v
template<typename T > constexpr bool xl::is_map_v = is_map<T>::value
Definition at line 111 of file library_extensions.h.
is_pair_v
template<typename T > constexpr bool xl::is_pair_v = is_pair<T>::value
Definition at line 119 of file library_extensions.h.
is_range_for_loop_able_v
template<class T > constexpr bool xl::is_range_for_loop_able_v = is_range_for_loop_able<T>::value
Definition at line 245 of file library_extensions.h.
is_std_array_v
template<typename T > constexpr bool xl::is_std_array_v = is_std_array<T>::value
Definition at line 608 of file library_extensions.h.