xl - xaxxon's library: std::__1 Namespace Reference
std::__1 Namespace Reference
Functions
template<class T1 , class T2 >
pair (T1 t1, T2 t) -> pair< T1, T2 >
Function Documentation
pair()
template<class T1 , class T2 > std::__1::pair (T1 t1, T2 t) -> pair< T1, T2 >
Referenced by xl::log::LogStatusFile::initialize_from_log(), precompiled_template(), xl::log::LogStatusFile::read(), and single_use_template().