xl - xaxxon's library: benchmark/regex_benchmark.cpp File Reference
regex_benchmark.cpp File Reference
#include <iostream>
#include <sstream>
#include <benchmark/benchmark.h>
#include <vector>
#include "regex/regexer.h"
Functions
static void std_regex_plain_match (benchmark::State &state)
BENCHMARK (std_regex_plain_match)
static void xl_regex_std_match (benchmark::State &state)
BENCHMARK (xl_regex_std_match)
static void xl_regex_pcre_match (benchmark::State &state)
BENCHMARK (xl_regex_pcre_match)
static void xl_std_regex_replace (benchmark::State &state)
BENCHMARK (xl_std_regex_replace)
static void xl_pcre_regex_replace (benchmark::State &state)
BENCHMARK (xl_pcre_regex_replace)
Function Documentation
std_regex_plain_match()
static void std_regex_plain_match (benchmark::State & state) static
Definition at line 14 of file regex_benchmark.cpp.
References BENCHMARK().
BENCHMARK() [1/5]
BENCHMARK (std_regex_plain_match)
Referenced by std_regex_plain_match(), xl_pcre_regex_replace(), xl_regex_pcre_match(), xl_regex_std_match(), and xl_std_regex_replace().
xl_regex_std_match()
static void xl_regex_std_match (benchmark::State & state) static
Definition at line 26 of file regex_benchmark.cpp.
References BENCHMARK(), and xl::RegexStd::match().
BENCHMARK() [2/5]
BENCHMARK (xl_regex_std_match)
xl_regex_pcre_match()
static void xl_regex_pcre_match (benchmark::State & state) static
Definition at line 43 of file regex_benchmark.cpp.
References BENCHMARK().
BENCHMARK() [3/5]
BENCHMARK (xl_regex_pcre_match)
xl_std_regex_replace()
static void xl_std_regex_replace (benchmark::State & state) static
Definition at line 62 of file regex_benchmark.cpp.
References BENCHMARK(), and xl::RegexStd::replace().
BENCHMARK() [4/5]
BENCHMARK (xl_std_regex_replace)
xl_pcre_regex_replace()
static void xl_pcre_regex_replace (benchmark::State & state) static
Definition at line 78 of file regex_benchmark.cpp.
References BENCHMARK().
BENCHMARK() [5/5]
BENCHMARK (xl_pcre_regex_replace)