xl - xaxxon's library: xl::templates::DefaultProviders< ProviderContainer > Struct Template Reference
xl::templates::DefaultProviders< ProviderContainer > Struct Template Reference
#include <provider.h>
Classes
struct can_get_provider_for_type
struct can_get_provider_for_type< T, std::enable_if_t< std::disjunction_v< has_get_provider_member< T >, has_get_provider_free_function< T >, has_get_provider_in_provider_container< T > > > >
struct has_get_provider_free_function
struct has_get_provider_free_function< T, std::enable_if_t< std::is_same_v< ProviderPtr, decltype(get_provider(std::declval< T >()))> > >
struct has_get_provider_in_provider_container
struct has_get_provider_in_provider_container< T, PC_COPY, std::void_t< decltype(PC_COPY::get_provider(std::declval< T >()))> >
struct has_get_provider_member
struct has_get_provider_member< T, std::enable_if_t< std::is_same_v< ProviderPtr, decltype(std::declval< T >().get_provider())> > >
class is_provider_callback_type
class is_provider_type
class is_provider_type< T, std::enable_if_t< std::is_same_v< std::string, std::result_of_t< Provider< remove_refs_and_wrapper_t< T > >(ProviderData &) > > > >
class Provider
class Provider< T, std::enable_if_t< can_get_provider_for_type_v< remove_refs_and_wrapper_t< T > > > >
class Provider< T, std::enable_if_t< is_provider_callback_type_v< T > > >
class Provider< T, std::enable_if_t< is_range_for_loop_able_v< remove_reference_wrapper_t< T > > &&!std::is_convertible_v< remove_reference_wrapper_t< T >, std::string > &&!is_map_v< remove_reference_wrapper_t< T > > > >
class Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >
class Provider< T, std::enable_if_t< is_template_for_v< std::unique_ptr, remove_reference_wrapper_t< T > > > >
class Provider< T, std::enable_if_t< std::is_convertible_v< remove_reference_wrapper_t< T >, std::string > > >
class Provider< T, std::enable_if_t< std::is_pointer_v< remove_reference_wrapper_t< T > > &&!std::is_same_v< std::decay_t< std::remove_pointer_t< remove_reference_wrapper_t< T > > >, char > > >
Static Public Member Functions
template<class... Ts>
static ProviderPtr make_provider (Ts &&... pairs)
template<class T >
static ProviderPtr make_provider (T &&t)
template<class R , class... Args, std::enable_if_t< is_provider_type_v< R >, int > = 0>
static ProviderPtr make_provider (R(*f)(Args...))
Static Public Attributes
template<class T >
static constexpr bool has_get_provider_in_provider_container_v = has_get_provider_in_provider_container<T>::value
template<class T >
static constexpr bool is_provider_type_v = is_provider_type<T>::value
template<class T >
static constexpr bool is_provider_callback_type_v = is_provider_callback_type<T>::value
template<class T >
static constexpr bool has_get_provider_member_v = has_get_provider_member<T>::value
template<class T >
static constexpr bool has_get_provider_free_function_v = has_get_provider_free_function<T>::value
template<class T >
static constexpr bool can_get_provider_for_type_v = can_get_provider_for_type<T>::value
Detailed Description
template<typename ProviderContainer>
struct xl::templates::DefaultProviders< ProviderContainer >
Definition at line 21 of file provider.h.
Member Function Documentation
make_provider() [1/3]
template<typename ProviderContainer> template<class... Ts> static ProviderPtr xl::templates::DefaultProviders< ProviderContainer >::make_provider (Ts &&... pairs) inline static
Definition at line 168 of file provider.h.
Referenced by xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::get_named_provider(), xl::templates::make_provider(), xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::unique_ptr, remove_reference_wrapper_t< T > > > >::operator()(), and xl::templates::DefaultProviders< ProviderContainer >::Provider< T, std::enable_if_t< is_template_for_v< std::map, remove_refs_and_wrapper_t< T > > > >::Provider().
make_provider() [2/3]
template<typename ProviderContainer> template<class T > static ProviderPtr xl::templates::DefaultProviders< ProviderContainer >::make_provider (T && t) inline static
Definition at line 215 of file provider.h.
make_provider() [3/3]
template<typename ProviderContainer> template<class R , class... Args, std::enable_if_t< is_provider_type_v< R >, int > = 0> static ProviderPtr xl::templates::DefaultProviders< ProviderContainer >::make_provider (R(*)(Args...) f) inline static
Definition at line 238 of file provider.h.
Member Data Documentation
has_get_provider_in_provider_container_v
template<typename ProviderContainer> template<class T > constexpr bool xl::templates::DefaultProviders< ProviderContainer >::has_get_provider_in_provider_container_v = has_get_provider_in_provider_container<T>::value static
Definition at line 40 of file provider.h.
is_provider_type_v
template<typename ProviderContainer> template<class T > constexpr bool xl::templates::DefaultProviders< ProviderContainer >::is_provider_type_v = is_provider_type<T>::value static
Definition at line 59 of file provider.h.
is_provider_callback_type_v
template<typename ProviderContainer> template<class T > constexpr bool xl::templates::DefaultProviders< ProviderContainer >::is_provider_callback_type_v = is_provider_callback_type<T>::value static
Definition at line 78 of file provider.h.
has_get_provider_member_v
template<typename ProviderContainer> template<class T > constexpr bool xl::templates::DefaultProviders< ProviderContainer >::has_get_provider_member_v = has_get_provider_member<T>::value inline static
Definition at line 92 of file provider.h.
has_get_provider_free_function_v
template<typename ProviderContainer> template<class T > constexpr bool xl::templates::DefaultProviders< ProviderContainer >::has_get_provider_free_function_v = has_get_provider_free_function<T>::value inline static
Definition at line 108 of file provider.h.
can_get_provider_for_type_v
template<typename ProviderContainer> template<class T > constexpr bool xl::templates::DefaultProviders< ProviderContainer >::can_get_provider_for_type_v = can_get_provider_for_type<T>::value inline static
Definition at line 128 of file provider.h.
The documentation for this struct was generated from the following file:
include/xl/templates/provider.h