xl - xaxxon's library: benchmark/templates.cpp File Reference
templates.cpp File Reference
#include <iostream>
#include <sstream>
#include <benchmark/benchmark.h>
#include "templates.h"
Functions
static void single_use_template (benchmark::State &state)
BENCHMARK (single_use_template)
static void precompiled_template (benchmark::State &state)
BENCHMARK (precompiled_template)
Function Documentation
single_use_template()
static void single_use_template (benchmark::State & state) static
Definition at line 14 of file templates.cpp.
References BENCHMARK(), and std::__1::pair().
BENCHMARK() [1/2]
BENCHMARK (single_use_template)
Referenced by precompiled_template(), and single_use_template().
precompiled_template()
static void precompiled_template (benchmark::State & state) static
Definition at line 26 of file templates.cpp.
References BENCHMARK(), xl::templates::Template::compile(), xl::templates::Template::fill(), and std::__1::pair().
BENCHMARK() [2/2]
BENCHMARK (precompiled_template)